import { ListView, Button, VerticalBox, LineEdit, ComboBox } from "std-widgets.slint";
import { PersonData, GroupData } from "types.slint";

export component AddPersonPage inherits Window {
    width: 340px;
    height: 380px;
    title: @tr("ADD_PERSON");

    in-out property <string> name;
    in-out property <string> surname;
    in-out property <int> rank;
    in-out property <int> methodology;
    property <bool> can_submit: !name.is-empty && !surname.is-empty;

    callback exit();
    callback submit();

    Rectangle {
        border-width: 2px;
        border-color: white;

        Button {
            x: parent.width - 60px;
            y: 10px;
            icon: @image-url("./../assets/images/close.svg");
            colorize-icon: true;
            clicked => { root.exit(); }
        }

        VerticalBox {
            spacing: 8px;
            padding: 12px;
            padding-top: 30px;

            Text { text: @tr("INPUT_NAME"); }
            LineEdit { text <=> root.name; }

            Text { text: @tr("INPUT_SURNAME"); }
            LineEdit { text <=> root.surname; }

            Text { text: @tr("RANK"); }
            ComboBox {
                current-index <=> root.rank;
                model: [
                    "RANK_NONE",
                    "RANK_FIRST_MALE",
                    "RANK_FIRST_FEMALE",
                    "RANK_SECOND_MALE",
                    "RANK_SECOND_FEMALE",
                    "RANK_THIRD_MALE",
                    "RANK_THIRD_FEMALE",
                    "RANK_FOURTH_MALE",
                    "RANK_FOURTH_FEMALE",
                    "RANK_FIFTH",
                    "RANK_SIXTH"
                ];
            }

            Text { text: @tr("METHODOLOGY"); }
            ComboBox {
                current-index <=> root.methodology;
                model: [
                    "CUB",
                    "SCOUT",
                    "VENTURESCOUT",
                    "ROVER"
                ];
            }

            Button {
                text: @tr("ADD_PERSON");
                enabled: can_submit;
                clicked => { root.submit(); }
            }
        }
    }
}

export component AddGroupPage inherits Window {
    width: 340px;
    height: 180px;
    title: @tr("ADD_GROUP");

    in-out property <string> name;
    property <bool> can_submit: !name.is-empty;

    callback exit();
    callback submit();

    Rectangle {
        border-width: 2px;
        border-color: white;

        Button {
            x: parent.width - 60px;
            y: 10px;
            icon: @image-url("./../assets/images/close.svg");
            colorize-icon: true;
            clicked => { root.exit(); }
        }

        VerticalBox {
            spacing: 8px;
            padding: 12px;
            padding-top: 30px;

            Text { text: @tr("INPUT_NAME"); }
            LineEdit { text <=> root.name; }

            Button {
                text: @tr("ADD_GROUP");
                enabled: can_submit;
                clicked => { root.submit(); }
            }
        }
    }
}

export component AddPerosnToGroupPage inherits Window {
    width: 340px;
    height: 180px;
    title: @tr("ADD_PERSON_TO_GROUP");

    in-out property <[string]> persons;
    in-out property <[string]> groups;

    in-out property <int> person;
    in-out property <int> group;
    property <bool> can_submit: true;

    callback check();
    callback exit();
    callback submit();

    Rectangle {
        border-width: 2px;
        border-color: white;

        Button {
            x: parent.width - 60px;
            y: 10px;
            icon: @image-url("./../assets/images/close.svg");
            colorize-icon: true;
            clicked => { root.exit(); }
        }

        VerticalBox {
            spacing: 8px;
            padding: 12px;
            padding-top: 30px;

            Text { text: @tr("CHOOSE_PEROSN"); }
            ComboBox {
                current-index <=> root.person;
                model: persons;
            }

            Text { text: @tr("CHOOSE_GROUP"); }
            ComboBox {
                current-index <=> root.group;
                model: groups;
            }

            Button {
                text: @tr("ADD_GROUP");
                enabled: can_submit;
                clicked => { root.submit(); }
            }
        }
    }
}
