import { VerticalBox, HorizontalBox, Button, CheckBox, GroupBox, ListView, StandardButton } from "std-widgets.slint";
import { Title } from "title.slint";
import { AddPersonPage, AddGroupPage } from "add_person.slint";
import { GroupsPanel } from "groups_panel.slint";
import { PersonData, GroupData } from "types.slint";
import "./../assets/fonts/Quicksand/static/Quicksand-Regular.ttf";
import "./../assets/fonts/Quicksand/static/Quicksand-Bold.ttf";

export component MainWindow inherits Window {
    title: "eWartownik";
    icon: @image-url("./../assets/images/logo.png");
    default-font-family: "Quicksand";
    width: 400px;
    height: 600px;

    in-out property <int> current_screen: 0; // 0 = main, 1 = persons, 2 = logs, 3 = setings
    in-out property <[PersonData]> people;
    in-out property <[GroupData]> groups;

    callback add_person_request(string, string, int, int);
    callback add_group_request(string);
    callback remove_person_request(int);
    
    function change_screen(index: int) {
        root.current_screen = index;
        nav_btn1.checked = index == 0;
        nav_btn2.checked = index == 1;
        nav_btn3.checked = index == 2;
        nav_btn4.checked = index == 3;
    }

    VerticalBox {
        spacing: 10px;
        padding: 0px;

        // -------------------------------
        // Main Screen
        if root.current_screen == 0: VerticalBox {
            spacing: 5px;

            Title { text: "eWartownik"; }
            GroupBox {
                title: @tr("CURRENT_PERSONEL_LIST");

                VerticalBox {
                    spacing: 5px;
                    // Current state of persons
                }
            }
            HorizontalBox {
                spacing: 10px;

                Button { text: @tr("GET_IN"); }
                Button { text: @tr("GET_OUT"); }
            }
        }

        // -------------------------------
        // Persons
        if root.current_screen == 1: Rectangle {
            
            VerticalLayout {
                spacing: 5px;

                Title { text: @tr("PERSONEL_LIST"); }
                /*ListView {
                    for p in root.people: HorizontalBox {
                        height: root.height * 0.05;
                        
                        Rectangle {
                            background: p.methodology;
                            width: 6px;
                            height: 6px;
                            border-radius: 6px;
                        }

                        Rectangle {
                            Text {
                                text: p.rank + " " + p.name + " " + p.surname;
                            }
                        }

                        Button {
                            icon: @image-url("./../assets/images/delete.svg");
                            colorize-icon: true;
                            clicked => { remove_person_request(p.id) }
                        }
                    }
                }*/

                GroupsPanel {
                    groups: root.groups;
                }

                Button { text: @tr("ADD_PERSON"); clicked => { add_person_modal.visible = true; } }
                Button { text: @tr("ADD_GROUP"); clicked => { add_group_modal.visible = true; } }
            }

            add_person_modal := Rectangle {
                visible: false;
                width: root.width;
                height: root.height;
                y: 0;
                background: #00000080;

                AddPersonPage {
                    x: (parent.width - self.width) / 2;
                    y: 50px;
                    
                    function clear() {
                        add_person_modal.visible = false;
                        self.name = "";
                        self.surname = "";
                        self.rank = 0;
                        self.methodology = 0;
                    }

                    exit => {
                        clear();
                    }

                    submit => {
                        root.add_person_request(self.name, self.surname, self.rank, self.methodology);
                        clear();
                    }
                }
            }

            add_group_modal := Rectangle {
                visible: false;
                width: root.width;
                height: root.height;
                y: 0;
                background: #00000080;

                AddGroupPage {
                    x: (parent.width - self.width) / 2;
                    y: 150px;
                    
                    function clear() {
                        add_group_modal.visible = false;
                        self.name = "";
                    }

                    exit => {
                        clear();
                    }

                    submit => {
                        root.add_group_request(self.name);
                        clear();
                    }
                }
            }
        }

        // -------------------------------
        // Logs
        if root.current_screen == 2: VerticalBox {
            spacing: 5px;

            Title { text: @tr("LOGS"); }
            ListView {}
        }

        // -------------------------------
        // Settings
        if root.current_screen == 3: VerticalBox {
            spacing: 5px;

            Title { text: @tr("SETTINGS"); }
        }

        // -------------------------------
        // Navigation Bar
        Rectangle {
            height: 50px;
            width: root.width;

            HorizontalBox {
                padding: 0px;
                spacing: 0px;

                nav_btn1 := Button {
                    icon: @image-url("./../assets/images/home.svg");
                    colorize-icon: true;
                    checkable: true;
                    checked: true;
                    clicked => { change_screen(0); }
                }
                nav_btn2 := Button {
                    icon: @image-url("./../assets/images/group.svg");
                    colorize-icon: true;
                    checkable: true;
                    clicked => { change_screen(1); }
                }
                nav_btn3 := Button {
                    icon: @image-url("./../assets/images/script.svg");
                    colorize-icon: true;
                    checkable: true;
                    clicked => { change_screen(2); }
                }
                nav_btn4 := Button {
                    icon: @image-url("./../assets/images/cog.svg");
                    colorize-icon: true;
                    checkable: true;
                    clicked => { change_screen(3); }
                }
            }
        }
    }
}
