export component IconButton {
    in property <image> icon;

    callback clicked();

    Rectangle {
        width: parent.width;
        height: parent.height;
        border-radius: 8px;
        border-width: 1px;
        border-color: #2a66c9; //! MAM DOSYĆ NA DZIŚ

        Image {
            source: icon;
            width: parent.width;
            height: parent.height;
            x: (parent.width - self.width) / 2;
            y: (parent.height - self.height) / 2;
        }

        TouchArea {
            clicked => { root.clicked(); }
        }
    }
}
